name: GitHub Actions

on:
  push:
    branches:
      - master

jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: master
      
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      
      - name: List files in the repository
        run: |
          dir ${{ github.workspace }}
      
      - run: echo "ðŸ This job's status is ${{ job.status }}."
      
      - name: Configure Git
        run: |
          git config --global user.name "ashwinjoy-art"
          git config --global user.email "ashwinjoy530@gmail.com"

      - name: Check if WSL Branch Exists
        id: check-branch
        run: |
          if git show-ref --verify --quiet refs/heads/wsl; then
            echo "branch_exists=true" >> $GITHUB_ENV
          else
            echo "branch_exists=false" >> $GITHUB_ENV
          fi

      - name: Create WSL Branch if it Doesn't Exist
        if: steps.check-branch.outputs.branch_exists == 'false'
        run: |
          git checkout -b wsl
          git push origin wsl

      - name: Checkout WSL Branch
        if: steps.check-branch.outputs.branch_exists == 'true'
        run: |
          git checkout wsl

      - name: Merge Master into WSL
        run: |
          git merge master --no-ff --commit -m "Syncing changes from master to wsl"
          git push origin wsl
